package com.undeadscythes.metaturtle;

/**
 * A single {@link Metadata} consists of a {@link #metaID metaID} and some
 * {@link Metadatable} data.
 *
 * @author UndeadScythes
 */
public class Metadata {
    private static final long serialVersionUID = 1L;

    private final String metaID;
    private Metadatable value;

    /**
     * Create a new {@link Metadata} item with a given {@link #metaID metaID}
     * and {@link Metadatable} data.
     */
    public Metadata(final String metaID, final Metadatable value) {
        this.metaID = metaID;
        this.value = value;
    }


    /**
     * Create a new {@link Metadata} item with a given {@link #metaID metaID}
     * and a {@link Metadatable} {@link Data} generated by a {@link String}.
     *
     * @see #Metadata(String, Metadatable) Metadata(String, Metadatable)
     */
    public Metadata(final String metaID, final String value) {
        this(metaID, new Data(value));
    }

    /**
     * Get the value of this data entity.
     */
    public Metadatable getValue() {
        return value;
    }

    /**
     * Override for {@link Object#equals} to provide a method of testing this
     * {@link #metaID metaID}.
     *
     * @return True if this {@link Metadata} has the specified
     * {@link #metaID metaID}
     */
    public boolean equals(final String metaID) {
        return this.metaID.equals(metaID);
    }

    public String getID() {
        return metaID;
    }

    /**
     * Change the {@link #value value} of this {@link Metadata}.
     *
     * @return Old {@link #value value}
     */
    public Metadatable setValue(final Data value) {
        final Metadatable oldValue = this.value;
        this.value = value;
        return oldValue;
    }

    /**
     * Change the {@link #value value} of this {@link Metadata} to a
     * {@link Data} generated by a given {@link String}.
     *
     * @see #setValue(Data)  setValue(Data)
     */
    public Metadatable setValue(final String value) {
        return setValue(new Data(value));
    }
}
